volumes:
  preservation_postgres_data: {}

services:
  storage:
    build:
      context: .
      dockerfile: Dockerfile.StorageApi
    ports:
      - "8001:8080"

  preservation:
    build:
      context: .
      dockerfile: Dockerfile.PreservationApi
    env_file:
      - .env
    ports:
      - "8002:8080"

  ui:
    build:
      context: .
      dockerfile: Dockerfile.UI
    env_file:
      - .env
    ports:
      - "8003:8080"  

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=preservation
    ports:
      - "5433:5432"
    volumes:
      - preservation_postgres_data:/var/lib/postgresql/data