volumes:
  preservation_postgres_data: {}

services:
  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_PASSWORD=preservation
    ports:
      - "5433:5432"
    volumes:
      - preservation_postgres_data:/var/lib/postgresql/data